version: '1'

services:
  postgres:
    image: postgres
    container_name: ecommerce
    restart: always
    environment: 
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 1234
        POSTGRES_DB: ecommerce
    ports: 
      - "5433:5432"
    volumes: 
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
